version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: esm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: student_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - esm_network

  adminer:
    image: adminer:latest
    container_name: esm_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - esm_network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  esm_network:
    driver: bridge
