version: '3.8'

# Dockerized application stack (frontend + backend + nginx)
# Reuses existing Postgres container `engrisk-postgres` via the external default network

services:
  backend:
    build:
      context: ../be
    container_name: engrisk-backend
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://engrisk_user:EngRisk2024!SecureDB#789@engrisk-postgres:5432/student_management
      JWT_SECRET: EngRisk2024!JWTSecretKey#456!Production
    ports:
      - "3001:3001"
    networks:
      - engrisk_net

  frontend:
    build:
      context: ../fe
    container_name: engrisk-frontend
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_URL: https://msjenny.io.vn/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - engrisk_net

  nginx:
    image: nginx:alpine
    container_name: engrisk-nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      # If SSL termination in container is needed later, map 443 as well and update config
      # - "443:443"
    volumes:
      - ./nginx.docker.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - engrisk_net

networks:
  engrisk_net:
    external: true
    name: engrisk-student-management_default


